apiVersion: apps/v1
kind: Deployment

metadata:
  name: paymentservice  
  labels:
    app: paymentservice


spec:
  selector:
    matchLabels:
      app: paymentservice
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%      
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: avasiliev/paymentservice:1.0
          