apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: avasiliev/hipster-frontend:1.0
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "PRODUCT_CATALOG_SERVICE_ADDR"  
    - name: CURRENCY_SERVICE_ADDR
      value: "CURRENCY_SERVICE_ADDR"  
    - name: CART_SERVICE_ADDR
      value: "CART_SERVICE_ADDR"  
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "RECOMMENDATION_SERVICE_ADDR"          
    - name: CHECKOUT_SERVICE_ADDR
      value: "CHECKOUT_SERVICE_ADDR"          
    - name: SHIPPING_SERVICE_ADDR
      value: "SHIPPING_SERVICE_ADDR"          
    - name: AD_SERVICE_ADDR
      value: "AD_SERVICE_ADDR"          



    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  
status: {}
