apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    web: simple
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: web # А в методичке нет указания называть именно так
      image: avasiliev/web:1.0 # Образ из которого создается контейнер
      readinessProbe:
        # Добавимп роверку готовности
        httpGet: # веб-сервера отдавать
          path: /index.html # контент
          port: 80
      livenessProbe:
        tcpSocket: 
          port: 8000

      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:1.32
      volumeMounts:
        - name: app
          mountPath: /app
      command: ["sh", "-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
  volumes:
    - name: app
      emptyDir: {}
